name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd platform; docker build . --file Dockerfile --tag agentgpt-platform:$(date +%s)
    - name: Build the Docker image
      run: cd next; docker build . --file Dockerfile --tag agentgpt-frontend:$(date +%s)
